name: CBA
channels:
  - defaults
dependencies:
  - @EXPLICIT
  - blas-1.0-mkl.conda
  - ca-certificates-2024.7.2-haa95532_0.conda
  - tzdata-2024a-h04d1e81_0.conda
  - vs2015_runtime-14.29.30133-h43f2093_4.conda
  - vc-14.2-h2eaa2aa_4.conda
  - abseil-cpp-20211102.0-hd77b12b_0.conda
  - aws-c-common-0.8.5-h2bbff1b_0.conda
  - bzip2-1.0.8-h2bbff1b_6.conda
  - c-ares-1.19.1-h2bbff1b_0.conda
  - gflags-2.2.2-hd77b12b_1.conda
  - intel-openmp-2023.1.0-h59b6b97_46320.conda
  - jpeg-9e-h2bbff1b_1.conda
  - lerc-3.0-hd77b12b_0.conda
  - libbrotlicommon-1.0.9-h2bbff1b_8.conda
  - libdeflate-1.17-h2bbff1b_1.conda
  - libwebp-base-1.3.2-h2bbff1b_0.conda
  - lz4-c-1.9.4-h2bbff1b_1.conda
  - openssl-3.0.14-h827c3e9_0.conda
  - re2-2022.04.01-hd77b12b_0.conda
  - snappy-1.1.10-h6c2663c_1.conda
  - sqlite-3.45.3-h2bbff1b_0.conda
  - tbb-2021.8.0-h59b6b97_0.conda
  - utf8proc-2.6.1-h2bbff1b_1.conda
  - xz-5.4.6-h8cc25b3_1.conda
  - yaml-0.2.5-he774522_0.conda
  - zlib-1.2.13-h8cc25b3_1.conda
  - aws-c-cal-0.5.20-h2bbff1b_0.conda
  - aws-c-compression-0.2.16-h2bbff1b_0.conda
  - aws-c-sdkutils-0.1.6-h2bbff1b_0.conda
  - aws-checksums-0.1.13-h2bbff1b_0.conda
  - glog-0.5.0-hd77b12b_1.conda
  - libbrotlidec-1.0.9-h2bbff1b_8.conda
  - libbrotlienc-1.0.9-h2bbff1b_8.conda
  - libevent-2.1.12-h56d1f94_1.conda
  - libpng-1.6.39-h8cc25b3_0.conda
  - libprotobuf-3.20.3-h23ce68f_0.conda
  - libssh2-1.11.0-h291bd65_0.conda
  - mkl-2023.1.0-h6b88ed4_46358.conda
  - python-3.9.19-h1aa4202_1.conda
  - zstd-1.5.5-hd43e919_2.conda
  - aws-c-io-0.13.10-h2bbff1b_0.conda
  - brotli-python-1.0.9-py39hd77b12b_8.conda
  - cloudpickle-2.2.1-py39haa95532_0.conda
  - colorama-0.4.6-py39haa95532_0.conda
  - freetype-2.12.1-ha860e81_0.conda
  - fsspec-2024.3.1-py39haa95532_0.conda
  - grpc-cpp-1.48.2-hfe90ff0_1.conda
  - heapdict-1.0.1-pyhd3eb1b0_0.conda
  - idna-3.7-py39haa95532_0.conda
  - libboost-1.82.0-h3399ecb_2.conda
  - libcurl-8.7.1-h86230a5_0.conda
  - libtiff-4.5.1-hd77b12b_0.conda
  - locket-1.0.0-py39haa95532_0.conda
  - lz4-4.3.2-py39h2bbff1b_0.conda
  - markupsafe-2.1.3-py39h2bbff1b_0.conda
  - mkl-service-2.4.0-py39h2bbff1b_1.conda
  - msgpack-python-1.0.3-py39h59b6b97_0.conda
  - orc-1.7.4-h623e30f_1.conda
  - packaging-24.1-py39haa95532_0.conda
  - psutil-5.9.0-py39h2bbff1b_0.conda
  - py4j-0.10.9.7-py39haa95532_0.conda
  - pycparser-2.21-pyhd3eb1b0_0.conda
  - python-lmdb-1.4.1-py39hd77b12b_0.conda
  - python-tzdata-2023.3-pyhd3eb1b0_0.conda
  - pytz-2024.1-py39haa95532_0.conda
  - pyyaml-6.0.1-py39h2bbff1b_0.conda
  - setuptools-69.5.1-py39haa95532_0.conda
  - six-1.16.0-pyhd3eb1b0_1.conda
  - sortedcontainers-2.4.0-pyhd3eb1b0_0.conda
  - tblib-1.7.0-pyhd3eb1b0_0.conda
  - toolz-0.12.0-py39haa95532_0.conda
  - tornado-6.4.1-py39h827c3e9_0.conda
  - wheel-0.43.0-py39haa95532_0.conda
  - win_inet_pton-1.1.0-py39haa95532_0.conda
  - xyzservices-2022.9.0-py39haa95532_1.conda
  - zipp-3.17.0-py39haa95532_0.conda
  - aws-c-event-stream-0.2.15-hd77b12b_0.conda
  - aws-c-http-0.6.25-h2bbff1b_0.conda
  - boost-cpp-1.82.0-h59b6b97_2.conda
  - cffi-1.16.0-py39h2bbff1b_1.conda
  - click-8.1.7-py39haa95532_0.conda
  - cytoolz-0.12.2-py39h2bbff1b_0.conda
  - importlib-metadata-7.0.1-py39haa95532_0.conda
  - jinja2-3.1.4-py39haa95532_0.conda
  - lcms2-2.12-h83e58a3_0.conda
  - numpy-base-1.26.4-py39h65a83cf_0.conda
  - openjpeg-2.4.0-h4afccc4_2.conda
  - partd-1.4.1-py39haa95532_0.conda
  - pip-24.0-py39haa95532_0.conda
  - pysocks-1.7.1-py39haa95532_0.conda
  - python-dateutil-2.9.0post0-py39haa95532_2.conda
  - zict-3.0.0-py39haa95532_0.conda
  - aws-c-auth-0.6.19-h2bbff1b_0.conda
  - aws-c-mqtt-0.7.13-h2bbff1b_0.conda
  - cryptography-42.0.5-py39h89fc84f_1.conda
  - dask-core-2024.5.0-py39haa95532_0.conda
  - libthrift-0.15.0-h4364b78_2.conda
  - pillow-10.3.0-py39h2bbff1b_0.conda
  - urllib3-2.2.2-py39haa95532_0.conda
  - aws-c-s3-0.1.51-h2bbff1b_0.conda
  - distributed-2024.5.0-py39haa95532_0.conda
  - dnspython-2.4.2-py39haa95532_0.conda
  - aws-crt-cpp-0.18.16-hd77b12b_0.conda
  - pymongo-4.6.3-py39hd77b12b_0.conda
  - aws-sdk-cpp-1.10.55-hd77b12b_0.conda
  - arrow-cpp-14.0.2-ha81ea56_1.conda
  - bottleneck-1.3.7-py39h9128911_0.conda
  - contourpy-1.2.0-py39h59b6b97_0.conda
  - mkl_fft-1.3.8-py39h2bbff1b_0.conda
  - mkl_random-1.2.4-py39h59b6b97_0.conda
  - numpy-1.26.4-py39h055cbcc_0.conda
  - numexpr-2.8.7-py39h2cd9be0_0.conda
  - pyarrow-14.0.2-py39h3d56cd0_0.conda
  - pandas-2.2.2-py39h5da7b33_0.conda
  - bokeh-3.4.1-py39h9909e9c_0.conda
  - dask-expr-1.1.0-py39haa95532_0.conda
  - pyspark-3.4.1-py39haa95532_0.conda
  - dask-2024.5.0-py39haa95532_0.conda
  - [0m
